# These are the requirements needed to build a conda
# environment on ReadTheDocs.
#
# Note that python requirements are intentionally left vague.
# We don't need the tests to pass, we only need to be able to
# import the packages.
name: env-readthedocs
channels:
    - conda-forge
dependencies:
    - python=3.8
    - gdal>=3
    - jsonschema
    - numpy
    - pygeometa
    - pygeoprocessing>=2.4.2
    - shapely
    - pyyaml
    - sphinx_rtd_theme
