name: Test pygeometadata

on: [push, pull_request]

defaults:
  run:
    shell: bash -l {0}

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          # Fetch all history so that setuptool_scm can build the correct
          # version string.
          fetch-depth: 0

      - name: setup-micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          # Grab requirements from pip-compatible requirements.txt
          environment-file: requirements.txt
          condarc: |
              channels:
                - conda-forge
          create-args: >-
              python=${{ matrix.python-version }}
              setuptools
              python-build
              pytest
          environment-name: pyenv

      - name: Build and Install
        run: |
            python -m build --wheel
            python -m pip install $(find dist -name "*.whl")

      - name: Test with pytest
        run: python -m pytest tests
